export const vocabularyData = [
  // A - Verbs
  { german: "ab", english: "off, from", category: "Preposition", type: "verb" },
  { german: "aber", english: "but", category: "Conjunction", type: "conjunction" },
  { german: "abfahren", english: "to depart", category: "Verb", type: "verb" },
  { german: "abgeben", english: "to hand in", category: "Verb", type: "verb" },
  { german: "abholen", english: "to pick up, collect", category: "Verb", type: "verb" },
  { german: "abschließen", english: "to lock, to conclude", category: "Verb", type: "verb" },
  { german: "Achtung", english: "Attention", category: "Noun", type: "noun" },
  { german: "Adresse", english: "Address", category: "Noun", type: "noun" },
  { german: "Ahnung", english: "idea, notion", category: "Noun", type: "noun" },
  { german: "aktiv", english: "active", category: "Adjective", type: "adjective" },
  { german: "aktuell", english: "current, up-to-date", category: "Adjective", type: "adjective" },
  { german: "allein", english: "alone", category: "Adjective", type: "adjective" },
  { german: "als", english: "as, when", category: "Conjunction", type: "conjunction" },
  { german: "also", english: "so, therefore", category: "Adjunction", type: "conjunction" },
  { german: "alt", english: "old", category: "Adjective", type: "adjective" },
  { german: "Alter", english: "Age", category: "Noun", type: "noun" },
  { german: "Ampel", english: "traffic light", category: "Noun", type: "noun" },
  { german: "an", english: "at, on", category: "Preposition", type: "preposition" },
  { german: "anbieten", english: "to offer", category: "Verb", type: "verb" },
  { german: "ändern", english: "to change, to alter", category: "Verb", type: "verb" },
  { german: "anders", english: "different(ly)", category: "Adverb", type: "adverb" },
  { german: "anfangen", english: "to begin, to start", category: "Verb", type: "verb" },
  { german: "Anfang", english: "beginning, start", category: "Noun", type: "noun" },
  { german: "Angst", english: "fear, anxiety", category: "Noun", type: "noun" },
  { german: "ankommen", english: "to arrive", category: "Verb", type: "verb" },
  { german: "Ankunft", english: "Arrival", category: "Noun", type: "noun" },
  { german: "anmachen", english: "to turn on, to light", category: "Verb", type: "verb" },
  { german: "anmelden", english: "to register, to sign up", category: "Verb", type: "verb" },
  { german: "Anmeldung", english: "registration, enrollment", category: "Noun", type: "noun" },
  { german: "Anrufbeantworter", english: "answering machine", category: "Noun", type: "noun" },
  { german: "anrufen", english: "to call, to phone", category: "Verb", type: "verb" },
  { german: "Anruf", english: "Call", category: "Noun", type: "noun" },
  { german: "Anschluss", english: "connection", category: "Noun", type: "noun" },
  { german: "ansehen", english: "to look at, to watch", category: "Verb", type: "verb" },
  { german: "antworten", english: "to answer", category: "Verb", type: "verb" },
  { german: "Antwort", english: "Answer", category: "Noun", type: "noun" },
  { german: "Anzeige", english: "advertisement, announcement", category: "Noun", type: "noun" },
  { german: "Anzug", english: "suit (clothing)", category: "Noun", type: "noun" },
  { german: "Apfel", english: "Apple", category: "Noun", type: "noun" },
  { german: "Apotheke", english: "pharmacy", category: "Noun", type: "noun" },
  { german: "Apparat", english: "device, apparatus", category: "Noun", type: "noun" },
  { german: "arbeiten", english: "to work", category: "Verb", type: "verb" },
  { german: "Arbeit", english: "work, job", category: "Noun", type: "noun" },
  { german: "arbeitslos", english: "unemployed", category: "Adjective", type: "adjective" },
  { german: "ärgern", english: "to get annoyed", category: "Verb", type: "verb" },
  { german: "arm", english: "poor", category: "Adjective", type: "adjective" },
  { german: "Arm", english: "arm (body part)", category: "Noun", type: "noun" },
  { german: "Artikel", english: "article, item", category: "Noun", type: "noun" },
  { german: "auch", english: "also, too", category: "Adverb", type: "adverb" },
  { german: "auf", english: "on, upon, to", category: "Preposition", type: "preposition" },
  { german: "aufhören", english: "to stop, to cease", category: "Verb", type: "verb" },
  { german: "aufmachen", english: "to open", category: "Verb", type: "verb" },
  { german: "aufpassen", english: "to pay attention", category: "Verb", type: "verb" },
  { german: "aufräumen", english: "to tidy up", category: "Verb", type: "verb" },
  { german: "aufregend", english: "exciting", category: "Adjective", type: "adjective" },
  { german: "aufstehen", english: "to get up, to stand up", category: "Verb", type: "verb" },
  { german: "Aufzug", english: "elevator, lift", category: "Noun", type: "noun" },
  { german: "Auge", english: "Eye", category: "Noun", type: "noun" },
  { german: "aus", english: "out of, from", category: "Preposition", type: "preposition" },
  { german: "Ausbildung", english: "training, education", category: "Noun", type: "noun" },
  { german: "Ausflug", english: "trip, excursion", category: "Noun", type: "noun" },
  { german: "ausfüllen", english: "to fill out (a form)", category: "Verb", type: "verb" },
  { german: "Ausgang", english: "Exit", category: "Noun", type: "noun" },
  { german: "ausgeben", english: "to spend (money)", category: "Verb", type: "verb" },
  { german: "ausgehen", english: "to go out", category: "Verb", type: "verb" },
  { german: "Auskunft", english: "Information", category: "Noun", type: "noun" },
  { german: "Ausland", english: "Foreign country", category: "Noun", type: "noun" },
  { german: "ausmachen", english: "to turn off, to arrange", category: "Verb", type: "verb" },
  { german: "auspacken", english: "to unpack", category: "Verb", type: "verb" },
  { german: "ausruhen", english: "to rest", category: "Verb", type: "verb" },
  { german: "aussehen", english: "to look, to appear", category: "Verb", type: "verb" },
  { german: "außer", english: "except for, besides", category: "Preposition", type: "preposition" },
  { german: "außerdem", english: "besides, moreover", category: "Adverb", type: "adverb" },
  { german: "außerhalb", english: "outside of", category: "Preposition", type: "preposition" },
  { german: "aussprechen", english: "to pronounce", category: "Verb", type: "verb" },
  { german: "aussteigen", english: "to get off (a train, bus)", category: "Verb", type: "verb" },
  { german: "Ausstellung", english: "exhibition", category: "Noun", type: "noun" },
  { german: "austragen", english: "to deliver (mail)", category: "Verb", type: "verb" },
  { german: "Ausweis", english: "ID card", category: "Noun", type: "noun" },
  { german: "Auto", english: "car", category: "Noun", type: "noun" },
  { german: "Autobahn", english: "highway, motorway", category: "Noun", type: "noun" },
  { german: "Automat", english: "automated machine", category: "Noun", type: "noun" },
  { german: "automatisch", english: "automatic", category: "Adjective", type: "adjective" },

  // B
  { german: "Baby", english: "baby", category: "Noun", type: "noun" },
  { german: "backen", english: "to bake", category: "Verb", type: "verb" },
  { german: "Bad", english: "bath, bathroom", category: "Noun", type: "noun" },
  { german: "baden", english: "to bathe", category: "Verb", type: "verb" },
  { german: "Bahn", english: "railway, train", category: "Noun", type: "noun" },
  { german: "Bahnhof", english: "train station", category: "Noun", type: "noun" },
  { german: "Bahnsteig", english: "platform", category: "Noun", type: "noun" },
  { german: "bald", english: "soon", category: "Adverb", type: "adverb" },
  { german: "Balkon", english: "balcony", category: "Noun", type: "noun" },
  { german: "Ball", english: "ball", category: "Noun", type: "noun" },
  { german: "Banane", english: "banana", category: "Noun", type: "noun" },
  { german: "Band", english: "tape, ribbon, band", category: "Noun", type: "noun" },
  { german: "Bank", english: "bank", category: "Noun", type: "noun" },
  { german: "bar", english: "cash (payment)", category: "Adjective", type: "adjective" },
  { german: "Basketball", english: "basketball", category: "Noun", type: "noun" },
  { german: "basteln", english: "to do crafts", category: "Verb", type: "verb" },
  { german: "Bauch", english: "stomach, belly", category: "Noun", type: "noun" },
  { german: "bauen", english: "to build", category: "Verb", type: "verb" },
  { german: "Baum", english: "tree", category: "Noun", type: "noun" },
  { german: "Baustelle", english: "construction site", category: "Noun", type: "noun" },
  { german: "beantworten", english: "to answer (a question)", category: "Verb", type: "verb" },
  { german: "bedanken", english: "to thank", category: "Verb", type: "verb" },
  { german: "bedeuten", english: "to mean", category: "Verb", type: "verb" },
  { german: "beeilen", english: "to hurry up", category: "Verb", type: "verb" },
  { german: "Bein", english: "leg", category: "Noun", type: "noun" },
  { german: "bekannt", english: "well-known, famous", category: "Adjective", type: "adjective" },
  { german: "Bekannte", english: "acquaintance", category: "Noun", type: "noun" },
  { german: "bekommen", english: "to get, to receive", category: "Verb", type: "verb" },
  { german: "beliebt", english: "popular", category: "Adjective", type: "adjective" },
  { german: "benutzen", english: "to use", category: "Verb", type: "verb" },
  { german: "bequem", english: "comfortable", category: "Adjective", type: "adjective" },
  { german: "beraten", english: "to advise", category: "Verb", type: "verb" },
  { german: "Berg", english: "mountain", category: "Noun", type: "noun" },
  { german: "berichten", english: "to report", category: "Verb", type: "verb" },
  { german: "Beruf", english: "profession, job", category: "Noun", type: "noun" },
  { german: "berühmt", english: "famous", category: "Adjective", type: "adjective" },
  { german: "Bescheid", english: "information", category: "Noun", type: "noun" },
  { german: "beschreiben", english: "to describe", category: "Verb", type: "verb" },
  { german: "beschweren", english: "to complain", category: "Verb", type: "verb" },
  { german: "besetzt", english: "occupied, busy", category: "Adjective", type: "adjective" },
  { german: "besichtigen", english: "to visit (sightsee)", category: "Verb", type: "verb" },
  { german: "besonders", english: "especially", category: "Adverb", type: "adverb" },
  { german: "bestätigen", english: "to confirm", category: "Verb", type: "verb" },
  { german: "bestehen", english: "to exist, to consist", category: "Verb", type: "verb" },
  { german: "bestellen", english: "to order", category: "Verb", type: "verb" },
  { german: "Besuch", english: "visit", category: "Noun", type: "noun" },
  { german: "besuchen", english: "to visit", category: "Verb", type: "verb" },
  { german: "Bett", english: "bed", category: "Noun", type: "noun" },
  { german: "bewerben", english: "to apply (for a job)", category: "Verb", type: "verb" },
  { german: "Bewerbung", english: "application", category: "Noun", type: "noun" },
  { german: "bewölkt", english: "cloudy", category: "Adjective", type: "adjective" },
  { german: "bezahlen", english: "to pay", category: "Verb", type: "verb" },
  { german: "Bibliothek", english: "library", category: "Noun", type: "noun" },
  { german: "Bier", english: "beer", category: "Noun", type: "noun" },
  { german: "Bild", english: "picture, image", category: "Noun", type: "noun" },
  { german: "billig", english: "cheap", category: "Adjective", type: "adjective" },
  { german: "Birne", english: "pear, lightbulb", category: "Noun", type: "noun" },
  { german: "bis", english: "until, to", category: "Preposition", type: "preposition" },
  { german: "bisschen", english: "a little", category: "Adverb", type: "adverb" },
  { german: "bitte", english: "please", category: "Adverb", type: "adverb" },
  { german: "Bitte", english: "request", category: "Noun", type: "noun" },
  { german: "bitten", english: "to ask, to request", category: "Verb", type: "verb" },
  { german: "bitter", english: "bitter", category: "Adjective", type: "adjective" },
  { german: "Blatt", english: "leaf, sheet of paper", category: "Noun", type: "noun" },
  { german: "bleiben", english: "to stay", category: "Verb", type: "verb" },
  { german: "Bleistift", english: "pencil", category: "Noun", type: "noun" },
  { german: "blöd", english: "stupid, annoying", category: "Adjective", type: "adjective" },
  { german: "Blog", english: "blog", category: "Noun", type: "noun" },
  { german: "blond", english: "blond", category: "Adjective", type: "adjective" },
  { german: "Blume", english: "flower", category: "Noun", type: "noun" },
  { german: "Bluse", english: "blouse", category: "Noun", type: "noun" },
  { german: "Bohne", english: "bean", category: "Noun", type: "noun" },
  { german: "böse", english: "angry, evil", category: "Adjective", type: "adjective" },
  { german: "braten", english: "to fry, to roast", category: "Verb", type: "verb" },
  { german: "brauchen", english: "to need", category: "Verb", type: "verb" },
  { german: "Brief", english: "letter", category: "Noun", type: "noun" },
  { german: "Briefmarke", english: "stamp", category: "Noun", type: "noun" },
  { german: "Brille", english: "glasses", category: "Noun", type: "noun" },
  { german: "bringen", english: "to bring", category: "Verb", type: "verb" },
  { german: "Brot", english: "bread", category: "Noun", type: "noun" },
  { german: "Brötchen", english: "bread roll", category: "Noun", type: "noun" },
  { german: "Brücke", english: "bridge", category: "Noun", type: "noun" },
  { german: "Buch", english: "book", category: "Noun", type: "noun" },
  { german: "buchen", english: "to book", category: "Verb", type: "verb" },
  { german: "Buchstabe", english: "letter (alphabet)", category: "Noun", type: "noun" },
  { german: "buchstabieren", english: "to spell", category: "Verb", type: "verb" },
  { german: "bunt", english: "colorful", category: "Adjective", type: "adjective" },
  { german: "Büro", english: "office", category: "Noun", type: "noun" },
  { german: "Bus", english: "bus", category: "Noun", type: "noun" },
  { german: "Butter", english: "butter", category: "Noun", type: "noun" },

  // C
  { german: "Café", english: "café", category: "Noun", type: "noun" },
  { german: "Cafeteria", english: "cafeteria", category: "Noun", type: "noun" },
  { german: "chatten", english: "to chat (online)", category: "Verb", type: "verb" },
  { german: "Chef", english: "boss", category: "Noun", type: "noun" },
  { german: "Club", english: "club", category: "Noun", type: "noun" },
  { german: "Comic", english: "comic book", category: "Noun", type: "noun" },
  { german: "Computer", english: "computer", category: "Noun", type: "noun" },
  { german: "Creme", english: "cream", category: "Noun", type: "noun" },

  // D
  { german: "da", english: "there, since", category: "Adverb", type: "adverb" },
  { german: "dabei", english: "to be present", category: "Verb", type: "verb" },
  { german: "dafür", english: "for it", category: "Adverb", type: "adverb" },
  { german: "dagegen", english: "against it", category: "Adverb", type: "adverb" },
  { german: "damals", english: "at that time", category: "Adverb", type: "adverb" },
  { german: "Dame", english: "lady", category: "Noun", type: "noun" },
  { german: "daneben", english: "next to it", category: "Adverb", type: "adverb" },
  { german: "Dank", english: "thanks", category: "Noun", type: "noun" },
  { german: "danke", english: "thank you", category: "Phrase", type: "phrase" },
  { german: "danken", english: "to thank", category: "Verb", type: "verb" },
  { german: "dann", english: "then", category: "Adverb", type: "adverb" },
  { german: "das", english: "the (neuter)", category: "Article", type: "article" },
  { german: "Datei", english: "file (computer)", category: "Noun", type: "noun" },
  { german: "Datum", english: "date (calendar)", category: "Noun", type: "noun" },
  { german: "dauern", english: "to last, to take time", category: "Verb", type: "verb" },
  { german: "denken", english: "to think", category: "Verb", type: "verb" },
  { german: "denn", english: "because, for", category: "Conjunction", type: "conjunction" },
  { german: "deshalb", english: "therefore", category: "Adverb", type: "adverb" },
  { german: "deutlich", english: "clear, distinct", category: "Adjective", type: "adjective" },
  { german: "dick", english: "thick, fat", category: "Adjective", type: "adjective" },
  { german: "Ding", english: "thing", category: "Noun", type: "noun" },
  { german: "direkt", english: "direct", category: "Adjective", type: "adjective" },
  { german: "Disco", english: "disco", category: "Noun", type: "noun" },
  { german: "diskutieren", english: "to discuss", category: "Verb", type: "verb" },
  { german: "doch", english: "yes (contradiction), but", category: "Particle", type: "particle" },
  { german: "Doppelzimmer", english: "double room", category: "Noun", type: "noun" },
  { german: "Dorf", english: "village", category: "Noun", type: "noun" },
  { german: "dort", english: "there", category: "Adverb", type: "adverb" },
  { german: "draußen", english: "outside", category: "Adverb", type: "adverb" },
  { german: "dringend", english: "urgent", category: "Adjective", type: "adjective" },
  { german: "drinnen", english: "inside", category: "Adverb", type: "adverb" },
  { german: "drüben", english: "over there", category: "Adverb", type: "adverb" },
  { german: "drücken", english: "to press, to push", category: "Verb", type: "verb" },
  { german: "drucken", english: "to print", category: "Verb", type: "verb" },
  { german: "Drucker", english: "printer", category: "Noun", type: "noun" },
  { german: "dumm", english: "stupid", category: "Adjective", type: "adjective" },
  { german: "dunkel", english: "dark", category: "Adjective", type: "adjective" },
  { german: "dünn", english: "thin", category: "Adjective", type: "adjective" },
  { german: "durch", english: "through, by", category: "Preposition", type: "preposition" },
  { german: "dürfen", english: "to be allowed to", category: "Modal Verb", type: "verb" },
  { german: "Durst", english: "thirst", category: "Noun", type: "noun" },
  { german: "Dusche", english: "shower", category: "Noun", type: "noun" },
  { german: "duschen", english: "to shower", category: "Verb", type: "verb" },

  // E
  { german: "E-Book", english: "e-book", category: "Noun", type: "noun" },
  { german: "echt", english: "real, genuine", category: "Adjective", type: "adjective" },
  { german: "Ecke", english: "corner", category: "Noun", type: "noun" },
  { german: "egal", english: "it doesn't matter", category: "Adjective", type: "adjective" },
  { german: "Ehefrau", english: "wife", category: "Noun", type: "noun" },
  { german: "Ehemann", english: "husband", category: "Noun", type: "noun" },
  { german: "Ei", english: "egg", category: "Noun", type: "noun" },
  { german: "eigen", english: "own", category: "Prefix", type: "adjective" },
  { german: "eigentlich", english: "actually", category: "Adverb", type: "adverb" },
  { german: "eilig", english: "in a hurry", category: "Adjective", type: "adjective" },
  { german: "einfach", english: "simple", category: "Adjective", type: "adjective" },
  { german: "Eingang", english: "entrance", category: "Noun", type: "noun" },
  { german: "einig", english: "some, several", category: "Prefix", type: "adjective" },
  { german: "einkaufen", english: "to go shopping", category: "Verb", type: "verb" },
  { german: "Einkaufszentrum", english: "shopping center", category: "Noun", type: "noun" },
  { german: "einladen", english: "to invite", category: "Verb", type: "verb" },
  { german: "Einladung", english: "invitation", category: "Noun", type: "noun" },
  { german: "einmal", english: "once", category: "Adverb", type: "adverb" },
  { german: "einpacken", english: "to pack", category: "Verb", type: "verb" },
  { german: "einsteigen", english: "to get in (a car)", category: "Verb", type: "verb" },
  { german: "eintragen", english: "to register, to enter", category: "Verb", type: "verb" },
  { german: "Eintritt", english: "admission, entrance", category: "Noun", type: "noun" },
  { german: "einverstanden", english: "to agree", category: "Phrase", type: "phrase" },
  { german: "einzeln", english: "single, individual", category: "Prefix", type: "adjective" },
  { german: "einziehen", english: "to move in", category: "Verb", type: "verb" },
  { german: "Eis", english: "ice, ice cream", category: "Noun", type: "noun" },
  { german: "E-Mail", english: "e-mail", category: "Noun", type: "noun" },
  { german: "Empfänger", english: "recipient", category: "Noun", type: "noun" },
  { german: "empfehlen", english: "to recommend", category: "Verb", type: "verb" },
  { german: "Ende", english: "end", category: "Noun", type: "noun" },
  { german: "enden", english: "to end", category: "Verb", type: "verb" },
  { german: "endlich", english: "finally", category: "Adverb", type: "adverb" },
  { german: "eng", english: "narrow, tight", category: "Adjective", type: "adjective" },
  { german: "entschuldigen", english: "to apologize", category: "Verb", type: "verb" },
  { german: "Entschuldigung", english: "apology, excuse", category: "Noun", type: "noun" },
  { german: "Erdgeschoss", english: "ground floor", category: "Noun", type: "noun" },
  { german: "Erfahrung", english: "experience", category: "Noun", type: "noun" },
  { german: "erinnern", english: "to remember", category: "Verb", type: "verb" },
  { german: "erkältet", english: "to have a cold", category: "Phrase", type: "phrase" },
  { german: "erklären", english: "to explain", category: "Verb", type: "verb" },
  { german: "erlauben", english: "to allow", category: "Verb", type: "verb" },
  { german: "erlaubt", english: "to be allowed", category: "Phrase", type: "phrase" },
  { german: "Erlaubnis", english: "permission", category: "Noun", type: "noun" },
  { german: "Ermäßigung", english: "discount, reduction", category: "Noun", type: "noun" },
  { german: "erreichen", english: "to reach, to achieve", category: "Verb", type: "verb" },
  { german: "erst", english: "first, only", category: "Adverb", type: "adverb" },
  { german: "Erwachsene", english: "adult", category: "Noun", type: "noun" },
  { german: "erzählen", english: "to tell (a story)", category: "Verb", type: "verb" },
  { german: "essen", english: "to eat", category: "Verb", type: "verb" },
  { german: "Essen", english: "food, meal", category: "Noun", type: "noun" },
  { german: "etwas", english: "something", category: "Adverb", type: "adverb" },

  // F
  { german: "Fach", english: "subject, compartment", category: "Noun", type: "noun" },
  { german: "fahren", english: "to depart, to drive away", category: "Verb", type: "verb" },
  { german: "Fahrkarte", english: "ticket", category: "Noun", type: "noun" },
  { german: "Fahrplan", english: "schedule", category: "Noun", type: "noun" },
  { german: "Fahrrad", english: "bicycle", category: "Noun", type: "noun" },
  { german: "fallen", english: "to fall", category: "Verb", type: "verb" },
  { german: "falsch", english: "wrong, false", category: "Adjective", type: "adjective" },
  { german: "Familie", english: "family", category: "Noun", type: "noun" },
  { german: "Familienname", english: "surname", category: "Noun", type: "noun" },
  { german: "Fan", english: "fan", category: "Noun", type: "noun" },
  { german: "fantastisch", english: "fantastic", category: "Adjective", type: "adjective" },
  { german: "Farbe", english: "color", category: "Noun", type: "noun" },
  { german: "fast", english: "almost", category: "Adverb", type: "adverb" },
  { german: "faul", english: "lazy", category: "Adjective", type: "adjective" },
  { german: "fehlen", english: "to be missing", category: "Verb", type: "verb" },
  { german: "Fehler", english: "mistake", category: "Noun", type: "noun" },
  { german: "Feier", english: "party, celebration", category: "Noun", type: "noun" },
  { german: "feiern", english: "to celebrate", category: "Verb", type: "verb" },
  { german: "Fenster", english: "window", category: "Noun", type: "noun" },
  { german: "Ferien", english: "vacation", category: "Noun", type: "noun" },
  { german: "fernsehen", english: "to watch TV", category: "Verb", type: "verb" },
  { german: "Fernseher", english: "television (set)", category: "Noun", type: "noun" },
  { german: "fertig", english: "to be finished", category: "Phrase", type: "adjective" },
  { german: "Fest", english: "party, festival", category: "Noun", type: "noun" },
  { german: "Festival", english: "festival", category: "Noun", type: "noun" },
  { german: "fett", english: "fat, greasy", category: "Adjective", type: "adjective" },
  { german: "Fieber", english: "fever", category: "Noun", type: "noun" },
  { german: "Film", english: "film, movie", category: "Noun", type: "noun" },
  { german: "finden", english: "to find", category: "Verb", type: "verb" },
  { german: "Firma", english: "company, firm", category: "Noun", type: "noun" },
  { german: "Fisch", english: "fish", category: "Noun", type: "noun" },
  { german: "fit", english: "to be fit", category: "Phrase", type: "adjective" },
  { german: "Flasche", english: "bottle", category: "Noun", type: "noun" },
  { german: "Fleisch", english: "meat", category: "Noun", type: "noun" },
  { german: "fleißig", english: "hard-working", category: "Adjective", type: "adjective" },
  { german: "fliegen", english: "to take off (airplane)", category: "Verb", type: "verb" },
  { german: "Flohmarkt", english: "flea market", category: "Noun", type: "noun" },
  { german: "Flug", english: "flight", category: "Noun", type: "noun" },
  { german: "Flughafen", english: "airport", category: "Noun", type: "noun" },
  { german: "Flugzeug", english: "airplane", category: "Noun", type: "noun" },
  { german: "Fluss", english: "river", category: "Noun", type: "noun" },
  { german: "Formular", english: "form", category: "Noun", type: "noun" },
  { german: "Fotoapparat", english: "camera", category: "Noun", type: "noun" },
  { german: "fotografieren", english: "to take a photo", category: "Verb", type: "verb" },
  { german: "Foto", english: "photo", category: "Noun", type: "noun" },
  { german: "Frage", english: "question", category: "Noun", type: "noun" },
  { german: "fragen", english: "to ask", category: "Verb", type: "verb" },
  { german: "Frau", english: "woman, wife, Mrs.", category: "Noun", type: "noun" },
  { german: "frei", english: "free, available", category: "Adjective", type: "adjective" },
  { german: "freiwillig", english: "voluntary", category: "Adjective", type: "adjective" },
  { german: "Freizeit", english: "free time", category: "Noun", type: "noun" },
  { german: "fremd", english: "foreign, strange", category: "Adjective", type: "adjective" },
  { german: "freuen", english: "to be happy", category: "Verb", type: "verb" },
  { german: "Freund", english: "friend", category: "Noun", type: "noun" },
  { german: "Freundin", english: "female friend", category: "Noun", type: "noun" },
  { german: "freundlich", english: "friendly", category: "Adjective", type: "adjective" },
  { german: "frisch", english: "fresh", category: "Adjective", type: "adjective" },
  { german: "früh", english: "early", category: "Adjective", type: "adjective" },
  { german: "früher", english: "earlier, formerly", category: "Adverb", type: "adverb" },
  { german: "Frühstück", english: "breakfast", category: "Noun", type: "noun" },
  { german: "frühstücken", english: "to eat breakfast", category: "Verb", type: "verb" },
  { german: "fühlen", english: "to feel", category: "Verb", type: "verb" },
  { german: "Führerschein", english: "driver's license", category: "Noun", type: "noun" },
  { german: "Führung", english: "tour, guidance", category: "Noun", type: "noun" },
  { german: "Fundsachen", english: "lost and found items", category: "Noun", type: "noun" },
  { german: "für", english: "for", category: "Preposition", type: "preposition" },
  { german: "furchtbar", english: "terrible", category: "Adjective", type: "adjective" },
  { german: "Fuß", english: "foot", category: "Noun", type: "noun" },
  { german: "Fußball", english: "soccer, football", category: "Noun", type: "noun" },

  // G - Continue with remaining letters...
  { german: "Gabel", english: "fork", category: "Noun", type: "noun" },
  { german: "ganz", english: "whole, quite", category: "Adjective", type: "adjective" },
  { german: "Garage", english: "garage", category: "Noun", type: "noun" },
  { german: "Garten", english: "garden", category: "Noun", type: "noun" },
  { german: "Gast", english: "guest", category: "Noun", type: "noun" },
  { german: "geben", english: "to give", category: "Verb", type: "verb" },
  { german: "geboren", english: "born", category: "Adjective", type: "adjective" },
  { german: "Geburtstag", english: "birthday", category: "Noun", type: "noun" },
  { german: "gefährlich", english: "dangerous", category: "Adjective", type: "adjective" },
  { german: "gefallen", english: "to like", category: "Verb", type: "verb" },
  { german: "gegen", english: "against", category: "Preposition", type: "preposition" },
  { german: "Gegenteil", english: "opposite", category: "Noun", type: "noun" },
  { german: "gegenüber", english: "opposite, across from", category: "Preposition", type: "preposition" },
  { german: "Gehalt", english: "salary", category: "Noun", type: "noun" },
  { german: "gehen", english: "to go, to walk", category: "Verb", type: "verb" },
  { german: "gehören", english: "to belong to", category: "Verb", type: "verb" },
  { german: "Geld", english: "money", category: "Noun", type: "noun" },
  { german: "Geldbörse", english: "wallet, purse", category: "Noun", type: "noun" },
  { german: "Gemüse", english: "vegetables", category: "Noun", type: "noun" },
  { german: "genau", english: "exact, precisely", category: "Adjective", type: "adjective" },
  { german: "genug", english: "enough", category: "Adverb", type: "adverb" },
  { german: "Gepäck", english: "luggage", category: "Noun", type: "noun" },
  { german: "gerade", english: "just now, straight", category: "Adverb", type: "adverb" },
  { german: "Gerät", english: "device, appliance", category: "Noun", type: "noun" },
  { german: "Gericht", english: "court, dish (meal)", category: "Noun", type: "noun" },
  { german: "gern", english: "gladly", category: "Adverb", type: "adverb" },
  { german: "Geschäft", english: "shop, business", category: "Noun", type: "noun" },
  { german: "Geschenk", english: "gift", category: "Noun", type: "noun" },
  { german: "Geschichte", english: "history, story", category: "Noun", type: "noun" },
  { german: "Geschirr", english: "dishes", category: "Noun", type: "noun" },
  { german: "Gesicht", english: "face", category: "Noun", type: "noun" },
  { german: "gestern", english: "yesterday", category: "Adverb", type: "adverb" },
  { german: "gesund", english: "healthy", category: "Adjective", type: "adjective" },
  { german: "Gesundheit", english: "health", category: "Noun", type: "noun" },
  { german: "Getränk", english: "drink", category: "Noun", type: "noun" },
  { german: "gewinnen", english: "to win", category: "Verb", type: "verb" },
  { german: "Gewitter", english: "thunderstorm", category: "Noun", type: "noun" },
  { german: "Gitarre", english: "guitar", category: "Noun", type: "noun" },
  { german: "Glas", english: "glass", category: "Noun", type: "noun" },
  { german: "glauben", english: "to believe", category: "Verb", type: "verb" },
  { german: "gleich", english: "same, in a moment", category: "Adjective", type: "adjective" },
  { german: "Gleis", english: "platform (train), track", category: "Noun", type: "noun" },
  { german: "Glück", english: "luck, happiness", category: "Noun", type: "noun" },
  { german: "glücklich", english: "happy", category: "Adjective", type: "adjective" },
  { german: "Glückwunsch", english: "congratulations", category: "Noun", type: "noun" },
  { german: "gratulieren", english: "to congratulate", category: "Verb", type: "verb" },
  { german: "grillen", english: "to barbecue", category: "Verb", type: "verb" },
  { german: "Grippe", english: "flu", category: "Noun", type: "noun" },
  { german: "groß", english: "big, tall", category: "Adjective", type: "adjective" },
  { german: "Größe", english: "size", category: "Noun", type: "noun" },
  { german: "Gruppe", english: "group", category: "Noun", type: "noun" },
  { german: "Gruß", english: "greeting", category: "Noun", type: "noun" },
  { german: "gültig", english: "to be valid", category: "Phrase", type: "adjective" },
  { german: "günstig", english: "favorable, cheap", category: "Adjective", type: "adjective" },
  { german: "gut", english: "good", category: "Adjective", type: "adjective" },
];
